# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ztd.ui'
#
# Created: Wed Mar 28 14:20:04 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1338, 797)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.back_week = QtGui.QPushButton(self.centralwidget)
        self.back_week.setMaximumSize(QtCore.QSize(40, 16777215))
        self.back_week.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.back_week.setObjectName(_fromUtf8("back_week"))
        self.horizontalLayout_2.addWidget(self.back_week)
        self.back = QtGui.QPushButton(self.centralwidget)
        self.back.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setObjectName(_fromUtf8("back"))
        self.horizontalLayout_2.addWidget(self.back)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.next = QtGui.QPushButton(self.centralwidget)
        self.next.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.next.setObjectName(_fromUtf8("next"))
        self.horizontalLayout_2.addWidget(self.next)
        self.next_week = QtGui.QPushButton(self.centralwidget)
        self.next_week.setMaximumSize(QtCore.QSize(40, 16777215))
        self.next_week.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.next_week.setObjectName(_fromUtf8("next_week"))
        self.horizontalLayout_2.addWidget(self.next_week)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.weekday1 = QtGui.QVBoxLayout()
        self.weekday1.setObjectName(_fromUtf8("weekday1"))
        self.daylabel1 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.daylabel1.setFont(font)
        self.daylabel1.setText(QtGui.QApplication.translate("MainWindow", "Monday", None, QtGui.QApplication.UnicodeUTF8))
        self.daylabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.daylabel1.setObjectName(_fromUtf8("daylabel1"))
        self.weekday1.addWidget(self.daylabel1)
        self.horizontalLayout.addLayout(self.weekday1)
        self.weekday2 = QtGui.QVBoxLayout()
        self.weekday2.setObjectName(_fromUtf8("weekday2"))
        self.daylabel2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.daylabel2.setFont(font)
        self.daylabel2.setText(QtGui.QApplication.translate("MainWindow", "Tuesday", None, QtGui.QApplication.UnicodeUTF8))
        self.daylabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.daylabel2.setObjectName(_fromUtf8("daylabel2"))
        self.weekday2.addWidget(self.daylabel2)
        self.horizontalLayout.addLayout(self.weekday2)
        self.weekday3 = QtGui.QVBoxLayout()
        self.weekday3.setObjectName(_fromUtf8("weekday3"))
        self.daylabel3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.daylabel3.setFont(font)
        self.daylabel3.setText(QtGui.QApplication.translate("MainWindow", "Wednesday", None, QtGui.QApplication.UnicodeUTF8))
        self.daylabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.daylabel3.setObjectName(_fromUtf8("daylabel3"))
        self.weekday3.addWidget(self.daylabel3)
        self.horizontalLayout.addLayout(self.weekday3)
        self.weekday4 = QtGui.QVBoxLayout()
        self.weekday4.setObjectName(_fromUtf8("weekday4"))
        self.daylabel4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.daylabel4.setFont(font)
        self.daylabel4.setText(QtGui.QApplication.translate("MainWindow", "Thursday", None, QtGui.QApplication.UnicodeUTF8))
        self.daylabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.daylabel4.setObjectName(_fromUtf8("daylabel4"))
        self.weekday4.addWidget(self.daylabel4)
        self.horizontalLayout.addLayout(self.weekday4)
        self.weekday5 = QtGui.QVBoxLayout()
        self.weekday5.setObjectName(_fromUtf8("weekday5"))
        self.daylabel5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.daylabel5.setFont(font)
        self.daylabel5.setText(QtGui.QApplication.translate("MainWindow", "Friday", None, QtGui.QApplication.UnicodeUTF8))
        self.daylabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.daylabel5.setObjectName(_fromUtf8("daylabel5"))
        self.weekday5.addWidget(self.daylabel5)
        self.horizontalLayout.addLayout(self.weekday5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.bottomPanel_btn = QtGui.QPushButton(self.centralwidget)
        self.bottomPanel_btn.setText(_fromUtf8(""))
        self.bottomPanel_btn.setObjectName(_fromUtf8("bottomPanel_btn"))
        self.verticalLayout.addWidget(self.bottomPanel_btn)
        self.bottomPnl = QtGui.QWidget(self.centralwidget)
        self.bottomPnl.setObjectName(_fromUtf8("bottomPnl"))
        self.bottomPanel = QtGui.QHBoxLayout(self.bottomPnl)
        self.bottomPanel.setMargin(0)
        self.bottomPanel.setObjectName(_fromUtf8("bottomPanel"))
        self.inbox = QtGui.QVBoxLayout()
        self.inbox.setObjectName(_fromUtf8("inbox"))
        self.label = QtGui.QLabel(self.bottomPnl)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "INBOX", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.inbox.addWidget(self.label)
        self.bottomPanel.addLayout(self.inbox)
        self.thisweek = QtGui.QVBoxLayout()
        self.thisweek.setObjectName(_fromUtf8("thisweek"))
        self.label_2 = QtGui.QLabel(self.bottomPnl)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "This week", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.thisweek.addWidget(self.label_2)
        self.bottomPanel.addLayout(self.thisweek)
        self.someday = QtGui.QVBoxLayout()
        self.someday.setObjectName(_fromUtf8("someday"))
        self.label_3 = QtGui.QLabel(self.bottomPnl)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Someday", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.someday.addWidget(self.label_3)
        self.bottomPanel.addLayout(self.someday)
        self.waiting = QtGui.QVBoxLayout()
        self.waiting.setObjectName(_fromUtf8("waiting"))
        self.label_4 = QtGui.QLabel(self.bottomPnl)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Waiting", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.waiting.addWidget(self.label_4)
        self.bottomPanel.addLayout(self.waiting)
        self.verticalLayout.addWidget(self.bottomPnl)
        self.delete_label = QtGui.QLabel(self.centralwidget)
        self.delete_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delete_label.setFont(font)
        self.delete_label.setText(QtGui.QApplication.translate("MainWindow", "Drag here to delete", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_label.setObjectName(_fromUtf8("delete_label"))
        self.verticalLayout.addWidget(self.delete_label)
        self.outdated = QtGui.QVBoxLayout()
        self.outdated.setContentsMargins(0, 0, -1, -1)
        self.outdated.setObjectName(_fromUtf8("outdated"))
        self.outdated_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.outdated_label.setFont(font)
        self.outdated_label.setText(QtGui.QApplication.translate("MainWindow", "There are some unfinished tasks in the past.", None, QtGui.QApplication.UnicodeUTF8))
        self.outdated_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.outdated_label.setObjectName(_fromUtf8("outdated_label"))
        self.outdated.addWidget(self.outdated_label)
        self.verticalLayout.addLayout(self.outdated)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1338, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

