# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ztd.ui'
#
# Created: Tue Mar 13 17:22:21 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1342, 605)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.back_week = QtGui.QPushButton(self.centralwidget)
        self.back_week.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.back_week.setObjectName(_fromUtf8("back_week"))
        self.gridLayout.addWidget(self.back_week, 0, 0, 1, 1)
        self.back = QtGui.QPushButton(self.centralwidget)
        self.back.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setObjectName(_fromUtf8("back"))
        self.gridLayout.addWidget(self.back, 0, 1, 1, 1)
        self.next_week = QtGui.QPushButton(self.centralwidget)
        self.next_week.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.next_week.setObjectName(_fromUtf8("next_week"))
        self.gridLayout.addWidget(self.next_week, 0, 5, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.weekday1 = QtGui.QVBoxLayout()
        self.weekday1.setObjectName(_fromUtf8("weekday1"))
        self.daylabel1 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.daylabel1.setFont(font)
        self.daylabel1.setText(QtGui.QApplication.translate("MainWindow", "Monday", None, QtGui.QApplication.UnicodeUTF8))
        self.daylabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.daylabel1.setObjectName(_fromUtf8("daylabel1"))
        self.weekday1.addWidget(self.daylabel1)
        self.horizontalLayout.addLayout(self.weekday1)
        self.weekday2 = QtGui.QVBoxLayout()
        self.weekday2.setObjectName(_fromUtf8("weekday2"))
        self.daylabel2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.daylabel2.setFont(font)
        self.daylabel2.setText(QtGui.QApplication.translate("MainWindow", "Tuesday", None, QtGui.QApplication.UnicodeUTF8))
        self.daylabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.daylabel2.setObjectName(_fromUtf8("daylabel2"))
        self.weekday2.addWidget(self.daylabel2)
        self.horizontalLayout.addLayout(self.weekday2)
        self.weekday3 = QtGui.QVBoxLayout()
        self.weekday3.setObjectName(_fromUtf8("weekday3"))
        self.daylabel3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.daylabel3.setFont(font)
        self.daylabel3.setText(QtGui.QApplication.translate("MainWindow", "Wednesday", None, QtGui.QApplication.UnicodeUTF8))
        self.daylabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.daylabel3.setObjectName(_fromUtf8("daylabel3"))
        self.weekday3.addWidget(self.daylabel3)
        self.horizontalLayout.addLayout(self.weekday3)
        self.weekday4 = QtGui.QVBoxLayout()
        self.weekday4.setObjectName(_fromUtf8("weekday4"))
        self.daylabel4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.daylabel4.setFont(font)
        self.daylabel4.setText(QtGui.QApplication.translate("MainWindow", "Thursday", None, QtGui.QApplication.UnicodeUTF8))
        self.daylabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.daylabel4.setObjectName(_fromUtf8("daylabel4"))
        self.weekday4.addWidget(self.daylabel4)
        self.horizontalLayout.addLayout(self.weekday4)
        self.weekday5 = QtGui.QVBoxLayout()
        self.weekday5.setObjectName(_fromUtf8("weekday5"))
        self.daylabel5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.daylabel5.setFont(font)
        self.daylabel5.setText(QtGui.QApplication.translate("MainWindow", "Friday", None, QtGui.QApplication.UnicodeUTF8))
        self.daylabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.daylabel5.setObjectName(_fromUtf8("daylabel5"))
        self.weekday5.addWidget(self.daylabel5)
        self.horizontalLayout.addLayout(self.weekday5)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 6)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.next = QtGui.QPushButton(self.centralwidget)
        self.next.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.next.setObjectName(_fromUtf8("next"))
        self.gridLayout.addWidget(self.next, 0, 4, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 3, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1342, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

